version: '3'
services:
  spark-tech-db-postgres:
    image: "postgres:13"
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: spark_net
      POSTGRES_USER: db_user
    ports:
      - 5433:5432
  python_app:
    depends_on:
      - spark-tech-db-postgres
    environment:
      - WAIT_HOSTS=spark-tech-db-postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
